blog/urls.py
from django.urls import path

from blog.views import add_post, add_theme, home, post, search_result, theme

app_name = 'blog'
urlpatterns = [
    path('', home, name='home'),
    path('post-<int:pk>/', post, name="post"),
    path('theme-<int:pk>/', theme, name="theme"),

    path('search-result/', search_result, name='search-result'),

    path('add/', add_post, name="add"),
    path('add-theme', add_theme, name='add-theme')
]

forum/urls.py
from django.urls import include, path
from django.views.generic import TemplateView
from rest_framework import routers

from forum.views.ajax import ajax_view
from forum.views.chat import add_message, chat, messages
from forum.views.comment import CreateCommentView
from forum.views.contact import ContactView
from forum.views.home import HomeView
from forum.views.mock import mock_request
from forum.views.post import CreatePostView, PostView, UpdatePostView
from forum.views.reach import ReachView
from forum.views.thread import ThreadView
from forum.viewsets.post import PostViewSet
from forum.viewsets.thread import ThreadViewset

router = routers.SimpleRouter()
router.register('thread', ThreadViewset, 'zzz')
router.register('thread/favs', ThreadViewset, 'zzz')

router.register('post', PostViewSet, )

app_name = 'forum'

urlpatterns = [
    path('', HomeView.as_view(), name="home"),

    path('api/', include(router.urls)),

    path('thread/<int:pk>/', ThreadView.as_view(), name="thread"),

    path('about/', TemplateView.as_view(template_name='pages/about.html')),

    path('post/<int:pk>/', PostView.as_view(), name="post"),
    path('post/create/', CreatePostView.as_view(), name="create-post"),
    path('post/update/<int:pk>/', UpdatePostView.as_view(), name="update-post"),
    path('post/delete/<int:pk>/', UpdatePostView.as_view(), name="delete-post"),

    path('comment/create/', CreateCommentView.as_view(), name="create-comment"),

    path('contact/', ContactView.as_view()),

    path('ajaxReachView/', ajax_view, name="ajax"),

    # chat ---
    path('chat/', chat, name="chat"),
    path('chat/messages/', messages, name="chat-messages"),
    path('chat/add/', add_message, name="chat-add"),

    path('reach/', ReachView.as_view()),

    path('mock/', mock_request, name="mock"),
]

itacademy/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path, re_path
from drf_yasg.views import get_schema_view
from rest_framework import permissions

from itacademy import scheme

schema_view = get_schema_view(
    scheme.api_info,
    public=True,
    permission_classes=(permissions.AllowAny,),
)

urlpatterns = [
    path('admin/', admin.site.urls),
    path('testuser/', include('testuser.urls', namespace='testuser')),
    path('', include('main.urls', namespace='main')),
    path('blog/', include('blog.urls', namespace='blog')),
    path('forum/', include('forum.urls', namespace='forum')),
    path('user/', include('user.urls', namespace='user')),

    re_path(
        r'^api/swagger(?P<format>\.json|\.yaml)$',
        schema_view.without_ui(cache_timeout=None),
        name='schema-json'
    ),
    path(
        'api/swagger/',
        # todo: выставить значение для cache. 0 отключает кеширование
        schema_view.with_ui('swagger', cache_timeout=0),
        name='schema-swagger-ui'
    ),
    path(
        'api/redoc/',
        schema_view.with_ui('redoc', cache_timeout=None),
        name='schema-redoc'
    ),
]


urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

forum/models/chat.py
from django.db import models


class Chat(models.Model):
    message = models.CharField(max_length=255)
    add_time = models.DateTimeField(auto_now_add=True)
    user = models.ForeignKey(
        'user.UserModel',
        on_delete=models.CASCADE,
        related_name='+'
    )

    class Meta:
        ordering = ['pk']

forum/models/comment.py
from django.db import models
from django.utils.translation import ugettext_lazy as _


class Comment(models.Model):
    user = models.ForeignKey(
        'user.UserModel',
        on_delete=models.CASCADE,
    )
    post = models.ForeignKey(
        'forum.Post',
        on_delete=models.CASCADE,
        related_name='comments'
    )
    content = models.TextField()
    add_time = models.DateTimeField(
        auto_now_add=True
    )

    class Meta:
        verbose_name = _('Comment')
        verbose_name_plural = _('Comments')

    def __str__(self):
        return self.content

    def get_content(self):
        return self.content

    def save(self, *args, **kwargs):
        self.content = self.content.replace('<script>', '')

        super().save(*args, **kwargs)
    #
    #     self.post.comment_cnt = self.post.comments.count()
    #     self.post.save()
    #
    # def delete(self, using=None, keep_parents=False):
    #     self.status = 'deleted'
    #     self.save()
    #

forum/models/post.py
from django.contrib.postgres.fields import ArrayField, JSONField
from django.db import models
from django.db.models.signals import post_delete, post_save
from django.dispatch import receiver
from django.urls import reverse

from forum.models import Comment


class Post(models.Model):
    thread = models.ForeignKey(
        'forum.Thread',
        on_delete=models.CASCADE,
        null=True,
        help_text='Some usefull help text'
    )
    user = models.ForeignKey(
        'user.UserModel',
        on_delete=models.CASCADE
    )
    title = models.CharField(max_length=255)
    content = models.TextField()

    add_time = models.DateTimeField(auto_now_add=True)
    edit_time = models.DateTimeField(auto_now=True)

    tags = models.ManyToManyField('forum.Tag', blank=True)

    rating = models.FloatField(
        null=True,
    )

    views_cnt = models.IntegerField(default=0)
    comment_cnt = models.IntegerField(default=0)

    tags_list = ArrayField(
        models.CharField(max_length=10),
        default=list
    )
    options = JSONField(
        default=dict
    )

    class Meta:
        ordering = ['pk']

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('forum:post', kwargs={'pk': self.pk})


@receiver([post_save, post_delete], sender=Comment)
def comment_post_save(sender, instance, *args, **kwargs):
    instance.post.comment_cnt = instance.post.comments.count()
    instance.post.save()

forum/models/rating.py
from django.db import models


class Rating(models.Model):
    user = models.ForeignKey(
        'user.UserModel',
        on_delete=models.CASCADE,
        related_name='+'
    )
    post = models.ForeignKey(
        'forum.Post',
        on_delete=models.CASCADE,
        related_name='+'
    )
    add_time = models.DateTimeField(auto_now_add=True)
    mark = models.PositiveSmallIntegerField()

forum/models/tag.py
from django.db import models


class Tag(models.Model):
    tag = models.CharField(max_length=64)

    def __str__(self):
        return self.tag

forum/models/thread.py
from django.db import models
from django.urls import reverse


class Thread(models.Model):

    parent = models.ForeignKey(
        'forum.Thread',
        on_delete=models.CASCADE,
        null=True,
        blank=True,
    )

    title = models.CharField(max_length=255)
    description = models.TextField()
    author = models.ForeignKey(
        'user.UserModel',
        on_delete=models.SET_NULL,
        null=True,
    )
    add_time = models.DateTimeField(auto_now_add=True)
    private = models.BooleanField(default=False)

    post_cnt = models.IntegerField(default=0)
    comment_cnt = models.IntegerField(default=0)

    last_post_time = models.DateTimeField(
        null=True,
        blank=True,
        editable=False
    )
    last_comment_time = models.DateTimeField(
        null=True,
        blank=True,
        editable=False
    )

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('forum:thread', kwargs={'pk': self.pk})

forum/forms.py
from django import forms
from django.conf import settings
from django.core.mail import send_mail
from django.forms import widgets
from django.template.loader import render_to_string

from forum.models import Comment, Post


class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ['thread', 'title', 'content']
        widgets = {
            'thread': widgets.Select(attrs={
                'class': 'form-control'
            }),
            'title': widgets.TextInput(attrs={
                'class': 'form-control'
            }),
            'content': widgets.Textarea(attrs={
                'class': 'form-control'
            }),
        }


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ['post', 'content']
        widgets = {
            'post': widgets.HiddenInput(),
            'content': widgets.Textarea(attrs={
                'class': 'form-control',
                'rows': 4,
            }),
        }


class ContactForm(forms.Form):
    name = forms.CharField()
    subject = forms.CharField()
    email = forms.EmailField()
    message = forms.CharField(
        widget=forms.Textarea(attrs={'rows': 4})
    )

    def send_email(self):
        cd = self.cleaned_data

        send_mail(
            subject=cd.get('subject'),
            message=render_to_string(
                'email/contact.html',
                {
                    'name': cd.get('name'),
                    'message': cd.get('message'),
                    'email': cd.get('email')
                }
            ),
            from_email=settings.DEFAULT_FROM_EMAIL,
            recipient_list=['dan.tyan@gmailcom'],
            fail_silently=True
        )

forum/views.py
from django.views.generic import DetailView, TemplateView

from forum.models import Thread


class HomeView(TemplateView):
    template_name = 'pages/home.html'

    def get_context_data(self, **kwargs):
        data = super().get_context_data(**kwargs)

        data['threads'] = Thread.objects.all()

        return data


class ThreadView(DetailView):
    template_name = 'pages/thread.html'
    model = Thread

forum/views/ajax.py
from datetime import datetime

from django.http import JsonResponse

from forum.forms import CommentForm


def ajax_view(request):
    form = CommentForm(request.POST)
    if form.is_valid():
        comment = form.save(commit=False)
        comment.user = request.user
        comment.save()

    return JsonResponse({
        "comment": '{} - {}'.format(datetime.now(), comment.content),
        'pk': comment.pk
    })

# def ajax_view(request):
#     return HttpResponse('text response')

# def ajax_view(request):
#     return HttpResponse('<h1 class="text-right">H1 ajax response</h1>')

# def ajax_view(request):
#     post = Post.objects.order_by('?').first()
#     return render(request, 'pages/block/ajax-post.html', {
#         'post': post
#     })

forum/views/chat.py
from django.contrib.auth.decorators import login_required
from django.http import JsonResponse
from django.shortcuts import render
from django.views.decorators.http import require_POST

from forum.models import Chat


def chat(request):
    _messages = Chat.objects.all()
    return render(request, 'chat/home.html', {
        'messages': _messages
    })


def messages(request):
    _messages = Chat.objects.all()

    return JsonResponse({
        "messages": [{"message": message.message} for message in _messages],
    })


@require_POST
@login_required
def add_message(request):
    message_text = request.POST.get('message')
    if message_text:
        _message = Chat.objects.create(
            message=message_text,
            user=request.user,
        )
        return JsonResponse({
            'message': _message.message,
            'user': _message.user_id,
        })

    return JsonResponse({
        'error': 'empty message',
    })

forum/views/comment.py
from django.urls import reverse
from django.views.generic import CreateView

from forum.forms import CommentForm
from forum.models import Comment


class CreateCommentView(CreateView):
    model = Comment
    form_class = CommentForm

    def form_valid(self, form):
        form.instance.user = self.request.user

        response = super().form_valid(form)

        # count = Comment.objects.filter(post=self.object.post).count()
        # # self.object.post.comment_cnt = F('comment_cnt') + 1
        # self.object.post.comment_cnt = count
        # self.object.post.save()

        return response

    def get_success_url(self):
        return reverse('forum:post', kwargs={'pk': self.object.post_id})

forum/views/contact.py
from django.urls import reverse_lazy
from django.views.generic.edit import FormView

from forum.forms import ContactForm


class ContactView(FormView):
    template_name = 'pages/contact.html'
    form_class = ContactForm
    success_url = reverse_lazy('forum:home')

    def form_valid(self, form):
        form.send_email()
        return super().form_valid(form)

forum/views/home.py
from django.views.generic import TemplateView

from forum.models import Thread


class HomeView(TemplateView):
    template_name = 'pages/home.html'

    def get_context_data(self, **kwargs):
        data = super().get_context_data(**kwargs)

        data['threads'] = Thread.objects.all()
        return data

forum/views/mock.py
from time import sleep

from django.http import HttpResponse


def some_func(*args, **kwargs):
    print('some_func')
    sleep(20)
    return 'bar'


def mock_request(request):
    print('mock_request')

    price = 150
    bonus = 50
    amount = price - bonus
    res = some_func(amount, 12, 2)
    print(res)
    print('after some func')
    return HttpResponse({})

forum/views/post.py
from django.db.models import F
from django.views.generic import CreateView, DeleteView, DetailView, UpdateView

from forum.forms import CommentForm, PostForm
from forum.models import Comment, Post


class CreatePostView(CreateView):
    model = Post
    template_name = 'pages/post/form.html'
    form_class = PostForm

    def form_valid(self, form):
        form.instance.user = self.request.user
        return super().form_valid(form)


class UpdatePostView(UpdateView):
    model = Post
    template_name = 'pages/post/form.html'


class DeletePostView(DeleteView):
    model = Post
    template_name = 'pages/post/form.html'


class PostView(DetailView):
    model = Post
    template_name = 'pages/post/post.html'

    def get(self, request, *args, **kwargs):
        response = super().get(request, *args, **kwargs)
        # BAD
        # self.object.views_cnt += 1
        # update post set views_cnt = 1

        # GOOD
        self.object.views_cnt = F('views_cnt') + 1
        # update post set views_cnt = views_cnt + 1

        self.object.save()

        return response

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['comment_form'] = CommentForm(initial={'post': self.object})
        context['comments'] = Comment.objects.filter(post=self.object)
        return context

forum/views/reach.py
from django.views.generic import TemplateView


class ReachView(TemplateView):
    template_name = 'pages/reach.html'

forum/views/thread.py
from django.views.generic import DetailView

from forum.models import Thread, Post


class ThreadView(DetailView):
    template_name = 'pages/thread.html'
    model = Thread

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        context['children'] = Thread.objects.filter(parent=self.object)
        context['posts'] = Post.objects.filter(thread=self.object)

        return context

forum/templates/pages/post/form.html
{% extends 'pages/_forum.html' %}


{% block content %}

    <div class="row">
        <div class="col">
            <div class="card">
                <div class="card-body">

                    <form action="" method="post">

                        {% for field in form %}

                            <fieldset class="form-group row {% if field.errors %}has-error{% endif %}">
                                <div class="col-md-12">
                                    <label for="{{ field.auto_id }}" class="">
                                        {{ field.label }}
                                    </label>

                                    {{ field }}

                                    {% for error in field.errors %}
                                        <div class="invalid-feedback" style="display: block">
                                            {{ error }}
                                        </div>
                                    {% endfor %}

                                    {% if field.help_text %}
                                        <small class="form-text text-muted">
                                            {{ field.help_text }}
                                        </small>
                                    {% endif %}
                                </div>

                            </fieldset>

                        {% endfor %}

                        <div>
                            {% csrf_token %}
                            <button type="submit" class="btn btn-primary">Save</button>
                        </div>
                    </form>


                </div>
            </div>
        </div>
    </div>





{% endblock %}

forum/templates/pages/post/post.html
{% extends 'pages/_forum.html' %}
{% load static %}

{% block content %}


    <div class="row mb-2">
        <div class="col">

            <div class="card">
                <div class="card-body">
                    <h1>{{ object.title }}</h1>
                    <div>
                        {{ object.content }}
                    </div>

                    <div>
                        {% for tag in object.tags_list %}
                            <a href="{{ tag }}">{{ tag }}</a>
                        {% endfor %}

                    </div>
                </div>

            </div>
        </div>
    </div>

    <div class="row mb-2">
        <div class="col">

            {% if comments %}
                <div class="card">
                    <ul class="list-group list-group-flush" id="comment-list">
                        {% for comment in comments %}

                            <li class="list-group-item">
                                {{ comment.content }}
                            </li>

                        {% endfor %}
                    </ul>
                </div>
            {% endif %}
        </div>
    </div>

    <div class="row mb-2">
        <div class="col">
            <div class="card">
                <div class="card-body">
                    <form action="{% url 'forum:create-comment' %}"
                          method="post"
                          id="comment-form"
                    >
                        {{ comment_form.as_p }}

                        <div>
                            {% csrf_token %}
                            <button
                                    id="ajax-button"
                                    type="submit"
                                    class="btn btn-primary">Save
                            </button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>

    <script src="{% static 'js/jquery-3.3.1.min.js' %}"></script>
    <script>

        $(document).ready(function () {
            $('#ajax-button').on('click', function () {

                $.post(
                    '{% url 'forum:ajax' %}',
                    $('#comment-form').serialize(),
                    function (response) {
                        $('<li/>')
                            .addClass('list-group-item')
                            .text(response.comment)
                            .appendTo($('#comment-list'));
                        $('#comment-form').trigger('reset')
                    }
                );

                return false;
            });

            setInterval(function () {
                console.log('interval');
            }, 5000);


        });

    </script>


{% endblock %}